import type { SchemaModel } from '@/models/schema';

// ===== Export Module =====
// Generates exportable representations from SchemaModel.

/**
 * Export SchemaModel as Mermaid ERD syntax.
 */
export function exportToMermaid(model: SchemaModel): string {
    let mermaid = 'erDiagram\n';

    for (const table of model.tables) {
        mermaid += '    ' + table.name + ' {\n';
        for (const field of table.fields) {
            const pk = field.isPrimaryKey ? ' PK' : '';
            const fk = field.isForeignKey ? ' FK' : '';
            mermaid += '        ' + field.type + ' ' + field.name + pk + fk + '\n';
        }
        mermaid += '    }\n';
    }

    for (const rel of model.relationships) {
        const relSymbol = rel.type === 'one-to-many'
            ? '||--o{'
            : rel.type === 'many-to-many'
                ? '}o--o{'
                : '||--||';
        mermaid += '    ' + rel.from.table + ' ' + relSymbol + ' ' + rel.to.table + ' : "' + rel.from.field + '"\n';
    }

    return mermaid;
}

/**
 * Export SchemaModel as Markdown documentation tables.
 */
export function exportToMarkdown(model: SchemaModel): string {
    let md = '# Schema Documentation\n\n';
    md += '_Generated by SchemaFlow_\n\n';

    for (const table of model.tables) {
        md += '## ' + table.name + '\n\n';
        md += '| Field | Type | PK | FK | Nullable | References |\n';
        md += '|-------|------|:--:|:--:|:--------:|------------|\n';

        for (const field of table.fields) {
            const ref = field.references
                ? field.references.table + '.' + field.references.field
                : '';
            md += '| ' + field.name +
                ' | `' + field.type + '`' +
                ' | ' + (field.isPrimaryKey ? '✓' : '') +
                ' | ' + (field.isForeignKey ? '✓' : '') +
                ' | ' + (field.isNullable ? '✓' : '✗') +
                ' | ' + ref +
                ' |\n';
        }
        md += '\n';
    }

    if (model.relationships.length > 0) {
        md += '## Relationships\n\n';
        md += '| From | To | Type |\n';
        md += '|------|----|------|\n';
        for (const rel of model.relationships) {
            md += '| ' + rel.from.table + '.' + rel.from.field +
                ' | ' + rel.to.table + '.' + rel.to.field +
                ' | ' + rel.type + ' |\n';
        }
        md += '\n';
    }

    return md;
}

/**
 * Export SchemaModel as TypeScript interfaces.
 */
export function exportToTypeScript(model: SchemaModel): string {
    let ts = '// Generated by SchemaFlow\n\n';

    for (const table of model.tables) {
        ts += 'export interface ' + table.name + ' {\n';
        for (const field of table.fields) {
            const tsType = sqlTypeToTs(field.type);
            const nullable = field.isNullable ? ' | null' : '';
            ts += '  ' + field.name + ': ' + tsType + nullable + ';\n';
        }
        ts += '}\n\n';
    }

    return ts;
}

function sqlTypeToTs(type: string): string {
    const upper = type.toUpperCase();
    if (/INT|INTEGER|SERIAL|BIGINT|SMALLINT/.test(upper)) return 'number';
    if (/FLOAT|DOUBLE|DECIMAL|NUMERIC|REAL/.test(upper)) return 'number';
    if (/BOOL/.test(upper)) return 'boolean';
    if (/DATE|TIME|TIMESTAMP/.test(upper)) return 'string';
    if (/TEXT|VARCHAR|CHAR|STRING|URL|EMAIL/.test(upper)) return 'string';
    if (/JSON|JSONB/.test(upper)) return 'Record<string, unknown>';
    if (/ARRAY/.test(upper)) return 'unknown[]';
    if (upper === 'OBJECT') return 'Record<string, unknown>';
    return 'unknown';
}
