import type { SchemaModel } from '@/models/schema';

// ===== Mock API Generator =====
// Generates mock REST API responses from SchemaModel.

/**
 * Generate a mock REST API specification from a SchemaModel.
 */
export function generateMockApi(model: SchemaModel): string {
    let output = '// Mock REST API — Generated by SchemaFlow\n';
    output += '// Base URL: /api/v1\n\n';

    for (const table of model.tables) {
        const name = table.name.toLowerCase();
        const plural = name.endsWith('s') ? name : name + 's';

        output += '// ───── ' + table.name + ' ─────\n\n';

        // GET all
        output += 'GET /api/v1/' + plural + '\n';
        output += 'Response: 200 OK\n';
        output += JSON.stringify(
            [generateMockRecord(table, model, 1), generateMockRecord(table, model, 2)],
            null,
            2
        ) + '\n\n';

        // GET by id
        output += 'GET /api/v1/' + plural + '/:id\n';
        output += 'Response: 200 OK\n';
        output += JSON.stringify(generateMockRecord(table, model, 1), null, 2) + '\n\n';

        // POST
        output += 'POST /api/v1/' + plural + '\n';
        output += 'Request Body:\n';
        const postBody: Record<string, unknown> = {};
        for (const field of table.fields) {
            if (!field.isPrimaryKey) {
                postBody[field.name] = generateMockValue(field.type, field.name);
            }
        }
        output += JSON.stringify(postBody, null, 2) + '\n';
        output += 'Response: 201 Created\n\n';

        output += '---\n\n';
    }

    return output;
}

function generateMockRecord(
    table: { name: string; fields: { name: string; type: string; isPrimaryKey: boolean }[] },
    _model: SchemaModel,
    seed: number
): Record<string, unknown> {
    const record: Record<string, unknown> = {};
    for (const field of table.fields) {
        record[field.name] = field.isPrimaryKey
            ? seed
            : generateMockValue(field.type, field.name, seed);
    }
    return record;
}

function generateMockValue(type: string, name: string, seed = 1): unknown {
    const upper = type.toUpperCase();
    const lower = name.toLowerCase();

    // Name-based heuristics
    if (lower === 'email') return 'user' + seed + '@example.com';
    if (lower === 'username' || lower === 'name') return 'user_' + seed;
    if (lower === 'title') return 'Sample Title ' + seed;
    if (lower === 'body' || lower === 'content' || lower === 'bio') return 'Lorem ipsum dolor sit amet...';
    if (lower.includes('url') || lower.includes('avatar')) return 'https://example.com/image' + seed + '.jpg';
    if (lower.includes('created') || lower.includes('updated')) return '2024-01-' + String(seed).padStart(2, '0') + 'T12:00:00Z';

    // Type-based fallbacks
    if (/INT|INTEGER|SERIAL|BIGINT|SMALLINT/.test(upper)) return seed * 10;
    if (/FLOAT|DOUBLE|DECIMAL|NUMERIC/.test(upper)) return seed * 10.5;
    if (/BOOL/.test(upper)) return seed % 2 === 1;
    if (/DATE|TIME|TIMESTAMP/.test(upper)) return '2024-01-' + String(seed).padStart(2, '0') + 'T12:00:00Z';
    if (/TEXT|VARCHAR|CHAR|STRING/.test(upper)) return 'sample_' + lower + '_' + seed;
    if (upper === 'EMAIL') return 'user' + seed + '@example.com';
    if (upper === 'URL') return 'https://example.com/' + seed;

    return 'mock_value_' + seed;
}
